language: python
python:
  - "2.7"
sudo: false
install:
  - python -m easy_install -U setuptools
  - git clone --depth=1 --branch=master https://github.com/tabatkins/bikeshed.git ./bikeshed
  - pip install pygments
  - pip install --upgrade setuptools
  - pip install --editable ./bikeshed
  - bikeshed update
script:
  bikeshed spec ./index.src.html
